"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to DEBUG = False for safety; enable explicitly in development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Comma-separated list of allowed hosts, e.g. "localhost,127.0.0.1,securevault.example.com"
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
  "django.contrib.admin",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
  "rest_framework",
  "corsheaders",
  "files",
]

# Add Cloudinary storage if CLOUDINARY_URL is set
# Note: We check this at module level, but actual import happens later in settings
# to avoid import errors if packages aren't installed
try:
    if 'CLOUDINARY_URL' in os.environ:
        INSTALLED_APPS.insert(0, 'cloudinary_storage')
        INSTALLED_APPS.insert(1, 'cloudinary')
except:
    pass

MIDDLEWARE = [
  "django.middleware.security.SecurityMiddleware",
  "whitenoise.middleware.WhiteNoiseMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "corsheaders.middleware.CorsMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
      ],
    },
  },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Use PostgreSQL in production (via DATABASE_URL), SQLite for local development
import dj_database_url

if 'DATABASE_URL' in os.environ:
    # Production: Use PostgreSQL from DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, 'data', 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
# Use Cloudinary in production, local storage in development
if 'CLOUDINARY_URL' in os.environ:
    # Production: Use Cloudinary for file storage
    # CLOUDINARY_URL format: cloudinary://api_key:api_secret@cloud_name
    try:
        import cloudinary
        import cloudinary.uploader
        from urllib.parse import urlparse
        
        # Parse CLOUDINARY_URL if provided, otherwise use individual env vars
        cloudinary_url = os.environ.get('CLOUDINARY_URL', '')
        if cloudinary_url:
            # Parse the URL: cloudinary://api_key:api_secret@cloud_name
            parsed = urlparse(cloudinary_url)
            cloud_name = parsed.hostname or os.environ.get('CLOUDINARY_CLOUD_NAME')
            api_key = parsed.username or os.environ.get('CLOUDINARY_API_KEY')
            api_secret = parsed.password or os.environ.get('CLOUDINARY_API_SECRET')
            
            cloudinary.config(
                cloud_name=cloud_name,
                api_key=api_key,
                api_secret=api_secret,
            )
        else:
            # Fallback to individual environment variables
            cloudinary.config(
                cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
                api_key=os.environ.get('CLOUDINARY_API_KEY'),
                api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
            )
        
        CLOUDINARY_STORAGE = {
            'CLOUDINARY_URL': cloudinary_url or os.environ.get('CLOUDINARY_URL', ''),
            'PREFIX': 'secure-vault',
        }
        
        DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
        MEDIA_URL = '/media/'
        MEDIA_ROOT = None  # Not used with Cloudinary
    except ImportError:
        # If cloudinary packages are not installed, fall back to local storage
        MEDIA_URL = '/media/'
        MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # Development: Use local file storage
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security headers (recommended for production)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# File upload security settings
MAX_UPLOAD_SIZE = int(os.environ.get('MAX_UPLOAD_SIZE', 10 * 1024 * 1024))  # 10MB default
TOTAL_STORAGE_LIMIT = int(os.environ.get('TOTAL_STORAGE_LIMIT', 200 * 1024 * 1024))  # 200MB default
ALLOWED_FILE_EXTENSIONS = os.environ.get('ALLOWED_FILE_EXTENSIONS', '').split(',') if os.environ.get('ALLOWED_FILE_EXTENSIONS') else []
BLOCKED_FILE_EXTENSIONS = os.environ.get('BLOCKED_FILE_EXTENSIONS', 'exe,com,bat,cmd,scr,pif,vbs,js,jar,msi,app').split(',')
ALLOWED_MIME_TYPES = os.environ.get('ALLOWED_MIME_TYPES', '').split(',') if os.environ.get('ALLOWED_MIME_TYPES') else []

# Sensitive document scanning
SENSITIVE_SCAN_ENABLED = os.environ.get('SENSITIVE_SCAN_ENABLED', 'true').lower() == 'true'
SENSITIVE_SCAN_EXTENSIONS = os.environ.get(
    'SENSITIVE_SCAN_EXTENSIONS',
    'pdf,txt,doc,docx,rtf'
).split(',')
SENSITIVE_SCAN_MAX_BYTES = int(os.environ.get('SENSITIVE_SCAN_MAX_BYTES', 2 * 1024 * 1024))
SENSITIVE_SCAN_MAX_TEXT_CHARS = int(os.environ.get('SENSITIVE_SCAN_MAX_TEXT_CHARS', 400_000))
SENSITIVE_SCAN_MAX_PDF_PAGES = int(os.environ.get('SENSITIVE_SCAN_MAX_PDF_PAGES', 25))
SENSITIVE_SPACY_MODEL = os.environ.get('SENSITIVE_SPACY_MODEL', 'en_core_web_sm')

# Temporary upload directory
UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'temp_uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'
).split(',')

# In production, prefer explicit CORS_ALLOWED_ORIGINS.
# We only allow all origins when DEBUG is True.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True
