# Generated by Django 4.2.23 on 2025-08-28 16:19

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, help_text='SHA-256 hash of file content', max_length=64, unique=True)),
                ('size', models.BigIntegerField(db_index=True, help_text='Size in bytes')),
                ('path', models.CharField(help_text='Relative path under MEDIA_ROOT', max_length=500)),
                ('ref_count', models.PositiveIntegerField(default=0, help_text='Number of files referencing this blob')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, db_index=True, help_text='File extension without dot', max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, help_text='MIME type', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddField(
            model_name='file',
            name='blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.fileblob'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['original_filename'], name='files_file_origina_63129f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['extension'], name='files_file_extensi_c10850_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['blob', 'uploaded_at'], name='files_file_blob_id_ae9429_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['sha256'], name='files_fileb_sha256_2fe16f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['size'], name='files_fileb_size_307788_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['created_at'], name='files_fileb_created_710ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['ref_count'], name='files_fileb_ref_cou_1d4bba_idx'),
        ),
    ]
