# Generated by Django 4.2.23 on 2025-08-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileblob_remove_file_size_file_extension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
    ]
