# Generated by Django 4.2.23 on 2025-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_size'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type', 'uploaded_at'], name='files_file_file_ty_a984e5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['extension', 'uploaded_at'], name='files_file_extensi_5c189f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at', 'blob'], name='files_file_uploade_0323c8_idx'),
        ),
    ]
